class Movies{

static String kannadaMovie[]={"kgf","milana","villain","robert","kantara","rangi taranga","lucia","myna","ugram","ratavara","kirataka","googly","ramachari","chowka","ranna","tagaru","tithi","duniya"," U turn","Dia","love mocktail","mugilpete","mungaru male 1","mungaru male 2","kotigobba"};
static String hindiMovie[]={"jab we met","dabang","pk","sholey","bahubali 1","bahubali 2","lagaan","gullu boy", "war","mission mangal","airlift","padmaavat","uri","article 15", "sooryavansi","bala","housefull","stree","tanhaji","badrinath ki dulhani","rustum","guru","raees","om shanti om","veer-zaara",};
static String englishMovie[]={"The Godfather","Pulp Fiction","The Dark Knight","Fight Club","Forrest Gump","The Matrix","Inception","Titanic","The Avengers","Jurassic Park","The Lion King","The Departed","The Silence of the Lambs","Goodfellas","The Terminator","The Social Network","The Prestige","The Shawshank Redemption","The Great Gatsby","Casablanca","Braveheart","The Wizard of Oz","The Green Mile","The Usual Suspects","Gone with the Wind"};
static String teluguMovie[]={"Arjun Reddy","Rangasthalam","Ala Vaikunthapurramuloo","Mahanati","Srimanthudu","Fidaa","Geetha Govindam","Atharintiki Daaredi","Eega","Magadheera","Janatha Garage","Bharat Ane Nenu","Nannaku Prematho","A Aa","Sarrainodu","Nuvvu Nenu","Khaidi No. 150","Gabbar Singh","Nenokkadine","Manam","Dookudu","Yevadu","Mirchi","Oopiri","Pokiri","Seethamma Vakitlo Sirimalle Chettu","Attarintiki","Daredi"};
static String tamilMovie[]={"Mersal","oke oka jeevitham","Kaithi","Vikram Vedha","Vada Chennai","Pariyerum Perumal","Asuran","Super Deluxe","Ratsasan","Peranbu","Viswasam","Kanchana 3","Petta","KGF Chapter 1 ","Irudhi Suttru","Raja Rani","Thani Oruvan","Vettai","Bigil","Theeran"," Adhigaaram Ondru","Aruvi","7G Rainbow Colony","Anbe Sivam","Aayirathil Oruvan","Kaadhal","Paruthiveeran","Evaru"};

public static void main (String args[]){


System.out.println("movies names");
System.out.println(kannadaMovie[0] + "\n" + kannadaMovie[1] + "\n" + kannadaMovie[2] + "\n" + kannadaMovie[3] + "\n" + kannadaMovie[4] + "\n" + kannadaMovie[5] + "\n" + kannadaMovie[6] + "\n" + kannadaMovie[7] + "\n" + kannadaMovie[8] + "\n" + kannadaMovie[9] + "\n" + kannadaMovie[10] + "\n" + kannadaMovie[11] + "\n" + kannadaMovie[12] + "\n" + kannadaMovie[13] + "\n" + kannadaMovie[14] + "\n" + kannadaMovie[15] + "\n" + kannadaMovie[16] + "\n" + kannadaMovie[17] + "\n" + kannadaMovie[18] + "\n" + kannadaMovie[19] + "\n" + kannadaMovie[20] + "\n" + kannadaMovie[21] + "\n" + kannadaMovie[22] + "\n" + kannadaMovie[23] + "\n" + kannadaMovie[24]);
System.out.println(hindiMovie[0] + "\n" + hindiMovie[1] + "\n" + hindiMovie[2] + "\n" + hindiMovie[3] + "\n" + hindiMovie[4] + "\n" + hindiMovie[5] + "\n" + hindiMovie[6] + "\n" + hindiMovie[7] + "\n" + hindiMovie[8] + "\n" + hindiMovie[9] + "\n" + hindiMovie[10] + "\n" + hindiMovie[11] + "\n" + hindiMovie[12] + "\n" + hindiMovie[13] + "\n" + hindiMovie[14] + "\n" + hindiMovie[15] + "\n" + hindiMovie[16] + "\n" + hindiMovie[17] + "\n" + hindiMovie[18] + "\n" + hindiMovie[19] + "\n" + hindiMovie[20] + "\n" + hindiMovie[21] + "\n" + hindiMovie[22] + "\n" + hindiMovie[23] + "\n" + hindiMovie[24]);
System.out.println(englishMovie[0] + "\n" + englishMovie[1] + "\n" + englishMovie[2] + "\n" + englishMovie[3] + "\n" + englishMovie[4] + "\n" + englishMovie[5] + "\n" + englishMovie[6] + "\n" + englishMovie[7] + "\n" + englishMovie[8] + "\n" + englishMovie[9] + "\n" + englishMovie[10] + "\n" + englishMovie[11] + "\n" + englishMovie[12] + "\n" + englishMovie[13] + "\n" + englishMovie[14] + "\n" + englishMovie[15] + "\n" + englishMovie[16] + "\n" + englishMovie[17] + "\n" + englishMovie[18] + "\n" + englishMovie[19] + "\n" + englishMovie[20] + "\n" + englishMovie[21] + "\n" + englishMovie[22] + "\n" + englishMovie[23] + "\n" + englishMovie[24]);
System.out.println(teluguMovie[0] + "\n" + teluguMovie[1] + "\n" + teluguMovie[2] + "\n" + teluguMovie[3] + "\n" + teluguMovie[4] + "\n" + teluguMovie[5] + "\n" + teluguMovie[6] + "\n" + teluguMovie[7] + "\n" + teluguMovie[8] + "\n" + teluguMovie[9] + "\n" + teluguMovie[10] + "\n" + teluguMovie[11] + "\n" + teluguMovie[12] + "\n" + teluguMovie[13] + "\n" + teluguMovie[14] + "\n" + teluguMovie[15] + "\n" + teluguMovie[16] + "\n" + teluguMovie[17] + "\n" + teluguMovie[18] + "\n" + teluguMovie[19] + "\n" + teluguMovie[20] + "\n" + teluguMovie[21] + "\n" + teluguMovie[22] + "\n" + teluguMovie[23] + "\n" + teluguMovie[24]);
System.out.println(tamilMovie[0] + "\n" + tamilMovie[1] + "\n" + tamilMovie[2] + "\n" + tamilMovie[3] + "\n" + tamilMovie[4] + "\n" + tamilMovie[5] + "\n" + tamilMovie[6] + "\n" + tamilMovie[7] + "\n" + tamilMovie[8] + "\n" + tamilMovie[9] + "\n" + tamilMovie[10] + "\n" + tamilMovie[11] + "\n" + tamilMovie[12] + "\n" + tamilMovie[13] + "\n" + tamilMovie[14] + "\n" + tamilMovie[15] + "\n" + tamilMovie[16] + "\n" + tamilMovie[17] + "\n" + tamilMovie[18] + "\n" + tamilMovie[19] + "\n" + tamilMovie[20] + "\n" + tamilMovie[21] + "\n" + tamilMovie[22] + "\n" + tamilMovie[23] + "\n" + tamilMovie[24]);
}
}